# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[workspace]

members = [
  "services/access_control/enclave",
  "services/authentication/enclave",
  "services/storage/enclave",
  "services/execution/enclave",
  "services/frontend/enclave",
  "services/management/enclave",
  "services/scheduler/enclave",
  "tests/unit/enclave",
  "tests/functional/enclave",
  "tests/integration/enclave",
  "tools/sgx_tool/enclave",
]

exclude = [
]

[patch.crates-io]
# Patched sgx crates to vendored, uncomment below crate when needed.

# Rust SGX SDK
sgx_alloc         = { path = "../../../third_party/rust-sgx-sdk/sgx_alloc" }
sgx_cov           = { path = "../../../third_party/rust-sgx-sdk/sgx_tests/cov" }
sgx_crypto        = { path = "../../../third_party/rust-sgx-sdk/sgx_crypto" }
sgx_libc          = { path = "../../../third_party/rust-sgx-sdk/sgx_libc" }
sgx_macros        = { path = "../../../third_party/rust-sgx-sdk/sgx_macros" }
sgx_rand          = { path = "../../../third_party/rust-sgx-sdk/sgx_rand" }
sgx_tprotected_fs = { path = "../../../third_party/rust-sgx-sdk/sgx_protected_fs/tfs" }
sgx_tse           = { path = "../../../third_party/rust-sgx-sdk/sgx_tse" }
sgx_tstd          = { path = "../../../third_party/rust-sgx-sdk/sgx_tstd" }
sgx_types         = { path = "../../../third_party/rust-sgx-sdk/sgx_types" }
sgx_trts          = { path = "../../../third_party/rust-sgx-sdk/sgx_trts" }
sgx_urts          = { path = "../../../third_party/rust-sgx-sdk/sgx_urts" }

crc               = { git = "https://github.com/mrhooray/crc-rs", rev = "86696be" }
simple_asn1       = { git = "https://github.com/acw/simple_asn1", rev = "7db7a48" }

# SGX crates
gbdt              = { git = "https://github.com/apache/incubator-teaclave-crates" }
getrandom         = { git = "https://github.com/apache/incubator-teaclave-crates" }
image             = { git = "https://github.com/apache/incubator-teaclave-crates" }
num_cpus          = { git = "https://github.com/apache/incubator-teaclave-crates" }
rand              = { git = "https://github.com/apache/incubator-teaclave-crates" }
rayon             = { git = "https://github.com/mesatee/rayon.git", branch = "teaclave" }
ring              = { git = "https://github.com/apache/incubator-teaclave-crates" }
rustface          = { git = "https://github.com/apache/incubator-teaclave-crates" }
rustls            = { git = "https://github.com/apache/incubator-teaclave-crates" }
rusty-machine     = { git = "https://github.com/apache/incubator-teaclave-crates" }
tantivy           = { git = "https://github.com/mesatee/tantivy.git", branch = "0.19.2" }
yasna             = { git = "https://github.com/sccommunity/yasna.rs", branch = "teaclave-sgx" }
