# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[package]
name = "teaclave_service_enclave_utils"
version = "0.5.1"
authors = ["Teaclave Contributors <dev@teaclave.apache.org>"]
description = "Teaclave enclave utils"
license = "Apache-2.0"
edition = "2021"

[features]
default = []
mesalock_sgx = [
    "teaclave_types/mesalock_sgx",
    "teaclave_attestation/mesalock_sgx",
    "teaclave_rpc/mesalock_sgx",
]
libos = [ 
    "teaclave_attestation/libos",
    "teaclave_rpc/app",
    "teaclave_types/app",
]
cov = ["sgx_cov", "sgx_macros"]

[dependencies]
anyhow     = { version = "1.0.26" }
env_logger = { version = "0.9.3", default_features = false }
log        = { version = "0.4.17", features = ["release_max_level_info"] }

teaclave_attestation                      = { path = "../../../attestation" }
teaclave_config                           = { path = "../../../config" }
teaclave_logger                           = { path = "../../../logger" }
teaclave_proto                            = { path = "../../proto" }
teaclave_rpc                              = { path = "../../../rpc" }
teaclave_service_enclave_utils_proc_macro = { path = "./proc_macro" }
teaclave_types                            = { path = "../../../types" }

sgx_cov     = { version = "2.0.0", optional = true }
sgx_macros  = { version = "2.0.0", optional = true }
